[project]
name = "mac-pdf-compression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "osxmetadata>=1.4.0",
    "pyobjc>=11.1",
    "tqdm>=4.67.1",
]
